echo ">baseline"
taskset -c 0,1,2 python3 test.py --test-manifest-list data/manifests/hkust_test_small_manifest.csv --batch-size 32 --labels-path data/labels/hkust_labels.json --lr 1e-4 --name test --save-folder save/ --save-every 2 --feat_extractor vgg_cnn --dropout 0.1 --num-enc-layers 2 --num-dec-layers 4 --num-heads 8 --dim-model 512 --dim-key 64 --dim-value 64 --dim-input 5120 --dim-inner 2048 --dim-emb 512 --shuffle --min-lr 0 --k-lr 1 --test-lang-list zh --trg-label-list data/labels/hkust_labels.json --early-stop cer,200 --combine_decoder --input_type char --clip --sample-rate 8000 --continue-from save/hkust/best_model.th >> log.out
echo ">r50"
taskset -c 0,1,2 python3 test.py --test-manifest-list data/manifests/hkust_test_small_manifest.csv --batch-size 32 --labels-path data/labels/hkust_labels.json --lr 1e-4 --name test --save-folder save/ --save-every 2 --feat_extractor vgg_cnn --dropout 0.1 --num-enc-layers 2 --num-dec-layers 4 --num-heads 8 --dim-model 512 --dim-key 64 --dim-value 64 --dim-input 5120 --dim-inner 2048 --dim-emb 512 --shuffle --min-lr 0 --k-lr 1 --test-lang-list zh --trg-label-list data/labels/hkust_labels.json --early-stop cer,200 --combine_decoder --input_type char --clip --sample-rate 8000 --is-factorized --r 50 --continue-from save/hkust_r_50/best_model.th >> log.out
echo ">r75"
taskset -c 0,1,2 python3 test.py --test-manifest-list data/manifests/hkust_test_small_manifest.csv --batch-size 32 --labels-path data/labels/hkust_labels.json --lr 1e-4 --name test --save-folder save/ --save-every 2 --feat_extractor vgg_cnn --dropout 0.1 --num-enc-layers 2 --num-dec-layers 4 --num-heads 8 --dim-model 512 --dim-key 64 --dim-value 64 --dim-input 5120 --dim-inner 2048 --dim-emb 512 --shuffle --min-lr 0 --k-lr 1 --test-lang-list zh --trg-label-list data/labels/hkust_labels.json --early-stop cer,200 --combine_decoder --input_type char --clip --sample-rate 8000 --is-factorized --r 75 --continue-from save/hkust_r_75/best_model.th >> log.out
echo ">r100"
taskset -c 0,1,2 python3 test.py --test-manifest-list data/manifests/hkust_test_small_manifest.csv --batch-size 32 --labels-path data/labels/hkust_labels.json --lr 1e-4 --name test --save-folder save/ --save-every 2 --feat_extractor vgg_cnn --dropout 0.1 --num-enc-layers 2 --num-dec-layers 4 --num-heads 8 --dim-model 512 --dim-key 64 --dim-value 64 --dim-input 5120 --dim-inner 2048 --dim-emb 512 --shuffle --min-lr 0 --k-lr 1 --test-lang-list zh --trg-label-list data/labels/hkust_labels.json --early-stop cer,200 --combine_decoder --input_type char --clip --sample-rate 8000 --is-factorized --r 100 --continue-from save/hkust_r_100/best_model.th >> log.out

